 Traceback (most recent call last):
  File "F:\python_execsice\Debugging\traceback.py", line 4, in <module>
    raise Exception ("This is the error message")
Exception: This is the error message
Traceback (most recent call last):
  File "F:\python_execsice\Debugging\traceback.py", line 4, in <module>
    raise Exception ("This is the error message")
Exception: This is the error message
